data1='enter first data'
data2='enter second data'
x=input(data1);
y=input(data2);
n=length(x);
X=log(x);
Y=log(y);
sX=sum(X);
sX2=sum(X.^2);
sY=sum(Y);
sXY=sum(X.*Y);
cof=[n sX;sX sX2];
free=[sY;sXY];
c=inv(cof)*free;
A=c(1)
a=exp(A)
b=c(2)
Y_avg=sY/n;
st=sum((Y-Y_avg).^2)
sr=sum((Y-A-b*X).^2)
sy_x=sqrt(sr/n-2)
r2=(st-sr)/st
r=sqrt(r2)
